
name: test-synology-chat

on:
  workflow_dispatch:   # 手動執行用

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Synology Chat
        run: |
          curl -X POST "${{ secrets.SHACHI_TOKEN}}" 'payload={"text": "This is a test"}'
          
